package com.myapps.fptool.model;

import java.util.ArrayList;
import java.util.List;

public class RuleGroup {
	private String productBasePath;
	private String scmUrl;
	private String softwareProductName;
	private String reportPath;
	private String reportFile;
	private List<String> applyRuleSets;
	private List<String> includeModules;
	private List<String> excludeModules;
	private List<String> flagModules;
	private List<String> includePackages;
	private List<String> excludePackages;
	private List<String> flagPackages;
	private List<String> findWords;
	private List<String> autoGeneratedTerms;

	public RuleGroup() {
		init();
	}

	private void init() {
		applyRuleSets = new ArrayList<>();
		includeModules = new ArrayList<>();
		excludeModules = new ArrayList<>();
		flagModules = new ArrayList<>();
		includePackages = new ArrayList<>();
		excludePackages = new ArrayList<>();
		flagPackages = new ArrayList<>();
		findWords = new ArrayList<>();
		autoGeneratedTerms = new ArrayList<>();
	}

	public String getProductBasePath() {
		return productBasePath;
	}

	public void setProductBasePath(String productBasePath) {
		this.productBasePath = productBasePath;
	}

	public String getScmUrl() {
		return scmUrl;
	}

	public void setScmUrl(String scmUrl) {
		this.scmUrl = scmUrl;
	}

	public String getSoftwareProductName() {
		return softwareProductName;
	}

	public void setSoftwareProductName(String softwareProductName) {
		this.softwareProductName = softwareProductName;
	}

	public String getReportPath() {
		return reportPath;
	}

	public void setReportPath(String reportPath) {
		this.reportPath = reportPath;
	}

	public String getReportFile() {
		return reportFile;
	}

	public void setReportFile(String reportFile) {
		this.reportFile = reportFile;
	}

	public List<String> getApplyRuleSets() {
		return applyRuleSets;
	}

	public void setApplyRuleSets(List<String> applyRuleSets) {
		this.applyRuleSets = applyRuleSets;
	}

	public List<String> getIncludeModules() {
		return includeModules;
	}

	public void setIncludeModules(List<String> includeModules) {
		this.includeModules = includeModules;
	}

	public List<String> getExcludeModules() {
		return excludeModules;
	}

	public void setExcludeModules(List<String> excludeModules) {
		this.excludeModules = excludeModules;
	}

	public List<String> getFlagModules() {
		return flagModules;
	}

	public void setFlagModules(List<String> flagModules) {
		this.flagModules = flagModules;
	}

	public List<String> getIncludePackages() {
		return includePackages;
	}

	public void setIncludePackages(List<String> includePackages) {
		this.includePackages = includePackages;
	}

	public List<String> getExcludePackages() {
		return excludePackages;
	}

	public void setExcludePackages(List<String> excludePackages) {
		this.excludePackages = excludePackages;
	}

	public List<String> getFlagPackages() {
		return flagPackages;
	}

	public void setFlagPackages(List<String> flagPackages) {
		this.flagPackages = flagPackages;
	}

	public List<String> getFindWords() {
		return findWords;
	}

	public void setFindWords(List<String> findWords) {
		this.findWords = findWords;
	}

	public List<String> getAutoGeneratedTerms() {
		return autoGeneratedTerms;
	}

	public void setAutoGeneratedTerms(List<String> autoGeneratedTerms) {
		this.autoGeneratedTerms = autoGeneratedTerms;
	}
}
